[package]
name = "libaria2-sys"
version = "0.1.0"
authors = ["Lucas Malandrino <lucas.malandrino@gmail.com>"]
edition = "2021"
links = "aria2"

[dependencies]
cxx = "^1.0.60"

[build-dependencies]
cxx-build = "^1.0.60"
pkg-config = "^0.3.24"

[dev-dependencies]
nix = "0.23.1"
